##print("Hello World!")
##print("Python can be used for printing")
##print("Each new print statement is printed on a new line!")
##print("We have extra characters that have special meaning too!")
##print("\tbackslash t prints out a tab\twhich is like several spaces")
##print("backslash n\nprints a new line\neach time you type it\n!")
##print("Vivan")
##print("V\nI\nV\nA\nN")
##print("Aug 30,2023\nIn french it's called\nAujourd'hui c'est trente aout deux-mille vingt trois\nwhich means\nToday is Augest 30th 2023")
##print('Aug 30,2023')
##print("Monday\nTuesday\nWednesday\nThursday\nFriday\nSaturday\nSunday")
##print("1\t2\t3\t4\t5\t6\t7\t8")
##print('HOW MUCH,HOW MUCH\t\t by Shel Silverstein')
print("How many slams in an old screen door?\n\tDepends how loud you shut it\nHow many slices in a bread?\n\tDepends how thin you cut it\nHow much good inside a day?\n\tDepends how good you live'em\nHow much love inside a friend?\n\tDepends how much you give'em")
